### ISSUE TITLE
Compilation failure: invalid operation: (name + "[") + k (mismatched types string and reflect.Value)

### ISSUE THREAD

**Issue by harold-padilla** [mitchellh/mapstructure#217]
We have a dependency on mapstructure but the compilation is failing with the following due to commit ddaf87dc9e7978bd12c4d8668511b0e7483de5f7 (https://github.com/mitchellh/mapstructure/commit/ddaf87dc9e7978bd12c4d8668511b0e7483de5f7#diff-7276b880a688d3af79f0a7b18e13df164968ac39766a475f3c91f9c445558e8f):

```
# github.com/mitchellh/mapstructure
../github.com/mitchellh/mapstructure/mapstructure.go:821:27: invalid operation: (name + "[") + k (mismatched types string and reflect.Value)
../github.com/mitchellh/mapstructure/mapstructure.go:1065:42: undefined: num
```

**Comment by harold-padilla** [comment]
The fix came in fast (https://github.com/mitchellh/mapstructure/commit/c0eda128fddecb427fba17df00ceaa9f0a864f5c). Thanks, @mitchellh
